sonar-scanner.bat `
  -D"sonar.organization=kaua-sousa-dev" `
  -D"sonar.projectKey=Kaua-Sousa-Dev_RobotGame"

 sonar.token=711a424114ff139023f8cb9b9d1070fa59ff722b

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io

sonar.sources=src

sonar.java.binaries=out